version: '3.9'
services:
  web:
    build: .
    command: gunicorn Tmart.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    container_name: postgredb
    image: postgres
    restart: always
    volumes:
      - ./postgre_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    expose:
      - 5432
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisData/data

  # celery_worker:
  #   build:
  #     context: .
  #   image: django_celery_example_celery_worker
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env/.dev-sample
  #   depends_on:
  #     - redis
  #     - db

  # celery_beat:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: django_celery_example_celery_beat
  #   command: /start-celerybeat
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env/.dev-sample
  #   depends_on:
  #     - redis
  #     - db


#   pgadmin:
#     image: dpage/pgadmin4
#     depends_on:
#       - db
#     ports:
#       - "5555:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#       PGADMIN_DEFAULT_PASSWORD: admin
#     restart: unless-stopped

# networks:
#   default:
#     name: postgre-service_default

volumes:
  postgres_data:
