version: '3.9'
services:
  web:
    build: .
    restart: 'always'
    volumes:
      - .:/app
      - static_volume:/app/staticfiles/
    env_file:
      - ./.env
    ports:
      - 8000:8000
    links:
     - db
    depends_on:
      - db
      - redis

  db:
    container_name: postgredb
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    command: celery -A Tmart worker -l info
    depends_on: 
      - "db"
      - "redis"
    env_file: .env  

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisData:/data


volumes:
  postgres_data:
  static_volume:
  redisData:
    external: false
  
networks:
  default:
      external:
          name: nginx-proxy
